// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcnCSfClwyofzDHdjyIIzVt-oX0iG87G4',
    appId: '1:1084204440913:web:c7b24769d929a683608770',
    messagingSenderId: '1084204440913',
    projectId: 'whatsapp-video-compressor',
    authDomain: 'whatsapp-video-compressor.firebaseapp.com',
    storageBucket: 'whatsapp-video-compressor.firebasestorage.app',
    measurementId: 'G-NL09J5S74L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV4MCYPsxRM0Tjxm9h7XRuy1x63i-ngQc',
    appId: '1:1084204440913:android:069301b7258b6bfc608770',
    messagingSenderId: '1084204440913',
    projectId: 'whatsapp-video-compressor',
    storageBucket: 'whatsapp-video-compressor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoHGkvqiJb35m4dWCY7dZ0BFWWiMvdDrI',
    appId: '1:1084204440913:ios:ae0262a931db7289608770',
    messagingSenderId: '1084204440913',
    projectId: 'whatsapp-video-compressor',
    storageBucket: 'whatsapp-video-compressor.firebasestorage.app',
    iosBundleId: 'com.example.whatsappVideoCompressor',
  );
}
